# Generated by Django 4.2.4 on 2023-10-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_d", "0001_initial"),
    ]

    operations = [
 
    ]
