# Generated by Django 4.2.4 on 2023-10-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_d", "0002_book_delete_item_delete_location"),
    ]

    operations = [
       
    ]
