# Generated by Django 4.2.4 on 2023-10-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_d", "0003_task_delete_book"),
    ]

    operations = [
     
    ]
