# Generated by Django 4.2.4 on 2023-10-05 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0004_tutorial_delete_task"),
    ]

    operations = [
        
    ]
